---
benchmark_type: lxd
categories:
  -
    name: Access, Authentication and Authorization
    sub_category:
      name: 5.1 Configure cron
      audit_tests:
        -
          name: '5.1.1 Ensure cron daemon is enabled (Automated)'
          description: The cron daemon is used to execute batch jobs on the system.
          audit:
            - 'systemctl is-enabled cron 2> /dev/null'
          remedeation: 'Based on your system configuration, run the appropriate one of the following commands to enable cron:
                        # systemctl --now enable cron'
          check_type: multi_param
          additional_info: 'Additional methods of enabling a service exist. Consult your distribution documentation for appropriate methods.'
          eval_expr: "'${0}' == 'enabled';"
        -
          name: '5.1.2 Ensure permissions on /etc/crontab are configured (Automated)'
          description: The /etc/crontab file is used by cron to control its own jobs.
                       The commands in this item make sure that root is the user and group owner of the file and that only the owner can access the file.
          audit:
            - 'stat /etc/crontab |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/crontab :
                         # chown root:root /etc/crontab
                         # chmod og-rwx /etc/crontab'
          check_type: multi_param
          eval_expr: "'${0}' == '(0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.1.3 Ensure permissions on /etc/cron.hourly are configured (Automated)'
          description: This directory contains system cron jobs that need to run on an hourly basis.
                        The files in this directory cannot be manipulated by the crontab command, but are instead edited by system administrators using a text editor.
                       The commands below restrict read/write and search access to user and group root, preventing regular users from accessing this directory.
          audit:
            - 'stat /etc/cron.hourly |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/cron.hourly:
                         # chown root:root /etc/cron.hourly
                        # chmod og-rwx /etc/cron.hourly'
          check_type: multi_param
          eval_expr: "'${0}' == '(0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.1.4 Ensure permissions on /etc/cron.daily are configured (Automated)'
          description: The /etc/cron.daily directory contains system cron jobs that need to run on a daily basis.
                        The files in this directory cannot be manipulated by the crontab command, but are instead edited by system administrators
                        using a text editor. The commands below restrict read/write and search access to user and group root, preventing regular users from accessing this directory.
          audit:
            - 'stat /etc/cron.daily |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/cron.daily:
                         # chown root:root /etc/cron.daily
                        # chmod og-rwx /etc/cron.daily'
          check_type: multi_param
          eval_expr: "'${0}' == '(0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.1.5 Ensure permissions on /etc/cron.weekly are configured (Automated)'
          description: The /etc/cron.weekly directory contains system cron jobs that need to run on a weekly basis.
                      The files in this directory cannot be manipulated by the crontab command, but are instead edited by system
                      administrators using a text editor. The commands below restrict read/write and search access to user and group root, preventing
                      regular users from accessing this directory.
          audit:
            - 'stat /etc/cron.weekly |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/cron.weekly:
                         # chown root:root /etc/cron.weekly
                        # chmod og-rwx /etc/cron.weekly'
          check_type: multi_param
          eval_expr: "'${0}' == '(0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.1.6 Ensure permissions on /etc/cron.monthly are configured (Automated)'
          description: The /etc/cron.monthly directory contains system cron jobs that need to run on a monthly basis.
                        The files in this directory cannot be manipulated by the crontab command, but are instead edited by system
                        administrators using a text editor. The commands below restrict read/write and search access to user and group
                        root, preventing regular users from accessing this directory.
          audit:
            - 'stat /etc/cron.monthly |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/cron.monthly:
                         # chown root:root /etc/cron.monthly
                        # chmod og-rwx /etc/cron.monthly'
          check_type: multi_param
          eval_expr: "'${0}' == '(0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.1.7 Ensure permissions on /etc/cron.d are configured (Automated)'
          description: The /etc/cron.d directory contains system cron jobs that need to run in a similar manner to the hourly,
                      daily weekly and monthly jobs from /etc/crontab , but require more granular control as to when they run.
                      The files in this directory cannot be manipulated by the crontab command, but are instead edited by system administrators
                      using a text editor. The commands below restrict read/write and search access to user and group root, preventing regular
                      users from accessing this directory.
          audit:
            - 'stat /etc/cron.d 2> /dev/null |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
          remedeation: 'Run the following commands to set ownership and permissions on /etc/cron.d:
                         # chown root:root /etc/cron.d
                        # chmod og-rwx /etc/cron.d'
          check_type: multi_param
          eval_expr: "'${0}' == '(0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)';"
        -
          name: '5.1.8 Ensure at/cron is restricted to authorized users (Automated)'
          description: Configure /etc/cron.allow and /etc/at.allow to allow specific users to use these services.
                      If /etc/cron.allow or /etc/at.allow do not exist, then /etc/at.deny and /etc/cron.deny are checked.
                      Any user not specifically defined in those files is allowed to use at and cron. By removing the files,
                      only users in /etc/cron.allow and /etc/at.allow are allowed to use at and cron. Note that even though
                      a given user is not listed in cron.allow , cron jobs can still be run as that user.
                      The cron.allow file only controls administrative access to the crontab command for scheduling and modifying cron jobs.
          audit:
            - 'stat /etc/cron.deny 2> /dev/null'
            - 'stat /etc/at.deny 2> /dev/null'
            - 'stat /etc/cron.allow 2> /dev/null |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''
            - 'stat /etc/at.allow 2> /dev/null |grep Access |awk -F "Access:" ''{print $2}'' |awk ''FNR <= 1'''

          remedeation: 'Run the following commands to remove /etc/cron.deny and /etc/at.deny and create and set permissions and ownership for /etc/cron.allow and /etc/at.allow :
                        # rm /etc/cron.deny
                        # rm /etc/at.deny
                        # touch /etc/cron.allow
                        # touch /etc/at.allow
                        # chmod o-rwx /etc/cron.allow
                        # chmod g-wx /etc/cron.allow
                        # chmod o-rwx /etc/at.allow
                        # chmod g-wx /etc/at.allow
                        # chown root:root /etc/cron.allow
                        # chown root:root /etc/at.allow'
          check_type: multi_param
          eval_expr: "'${0}' == ''; && '${1}' == ''; && '${2}' == '(0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    0/    root)' && '${3}' == '(0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    0/    root)';"

