Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "172.30.1.5"
  config.vm.network "forwarded_port", guest: 2345, host: 2345
config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 4048
  end
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.auto_update = false
  end
    config.vm.provision "shell" do |s|
    	s.path = "setup.sh"
    end 
end
